define OUR_AS = 4242421258;
define OUR_IP = 172.21.118.195;
define OUR_IP_V6 = fd49:1b9:8a02:feed::2;
define OUR_NET = 172.21.118.192/27;
define OUR_NET6 = fd49:1b9:8a02::/48;
define OUR_NETSET = [172.21.118.192/27+];
define OUR_NETSET6 = [fd49:1b9:8a02::/48+];

# Helper functions

function is_valid_net_v6() -> bool {
  return net ~ [
    fd00::/8{44,64} # ULA address space as per RFC 4193
  ];
}

function is_self_net() -> bool {
  return net ~ OUR_NETSET;
}

function is_self_net_v6() -> bool {
  return net ~ OUR_NETSET6;
}

function is_valid_net() -> bool {
  return net ~ [
    172.20.0.0/14{21,29}, # dn42
    172.20.0.0/24{28,32}, # dn42 Anycast
    172.21.0.0/24{28,32}, # dn42 Anycast
    172.22.0.0/24{28,32}, # dn42 Anycast
    172.23.0.0/24{28,32}, # dn42 Anycast
    172.31.0.0/16+,       # ChaosVPN
    10.100.0.0/14+,       # ChaosVPN
    10.127.0.0/16+,       # neonetwork
    10.0.0.0/8{15,24}     # Freifunk.net
  ];
}

protocol static {
    route OUR_NET reject;

    ipv4 {
        import all;
        export none;
    };
}

protocol static {
    route OUR_NET6 reject;

    ipv6 {
        import all;
        export none;
    };
}

include "defaults.d/*.conf";
include "templates.d/*.conf";
include "peers.d/*.conf";