roa4 table dn42_roa;
roa6 table dn42_roa_v6;

protocol rpki rpki_dn42 {
  roa4 { table dn42_roa; };
  roa6 { table dn42_roa_v6; };

  remote "rpki.dn42.launchpadx.top" port 8082;

  retry keep 90;
  refresh keep 900;
  expire keep 172800;
}