template bgp dn42_peer {
    local as OUR_AS;
    path metric on;

    ipv4 {
        import filter {
            if !is_valid_net() || is_self_net() then { reject; }
            if roa_check(dn42_roa, net, bgp_path.last) != ROA_VALID then {
                print "ROA check failed for ", net, " ASN ", bgp_path.last;
                reject;
            } else accept;
        };
        export filter {
            if is_valid_net() && source ~ [RTS_STATIC, RTS_BGP] then {
                accept;
            } else reject; 
        };
    };
    
    ipv6 {
        import filter {
            if !is_valid_net_v6() || is_self_net_v6() then { reject; }
            if roa_check(dn42_roa_v6, net, bgp_path.last) != ROA_VALID then {
                print "ROA check failed for ", net, " ASN ", bgp_path.last;
                reject;
            } else accept;
        };
        export filter {
            if is_valid_net_v6() && source ~ [RTS_STATIC, RTS_BGP] then {
                accept;
            } else reject; 
        };
    };
}