template bgp ibgp_edge_peer_mp {
    local as OUR_AS;

    ipv4 {
        import all;
        export filter {
            if is_valid_net() && source ~ [RTS_BGP, RTS_OSPF] then {
                accept;
            } else reject; 
        };
        next hop self;
        extended next hop on;
    };

    ipv6 {
        import all;
        export filter {
            if is_valid_net_v6() && source ~ [RTS_BGP, RTS_OSPF] then {
                accept;
            } else reject; 
        };
        next hop self;
    };

    direct;
}